import { readFileSync } from "node:fs"
import { join } from "node:path"

import { describe, expect, it } from "vitest"

const projectRoot = process.cwd()

function readSource(relativePath: string) {
  return readFileSync(join(projectRoot, relativePath), "utf8")
}

describe("detect console timeline regressions", () => {
  it("removes the 2D orthographic agent view while keeping the 3D, timeline, and graph entries", () => {
    const source = readSource("components/detect/DetectConsole.tsx")

    expect(source).not.toContain('"2d"')
    expect(source).not.toContain("'2d'")
    expect(source).not.toContain("2D 正交")
    expect(source).not.toContain('viewMode !== "timeline"')
    expect(source).toContain('"3d" | "timeline" | "graph"')
    expect(source).toContain("BentoScene")
    expect(source).toContain("EvidenceTimeline")
    expect(source).toContain("ProvenanceGraphView")
  })

  it("renders challenger round separators instead of per-card flow labels", () => {
    const source = readSource("components/detect/EvidenceTimeline.tsx")

    expect(source).toContain("phaseRound")
    expect(source).toContain("buildRoundSeparators")
    expect(source).toContain("challengerRound")
    expect(source).toContain("`R${round}`")
    expect(source).not.toContain("formatRoundLabel")
    expect(source).not.toContain("Forensics R")
    expect(source).not.toContain("流程 ${entry.round}")
    expect(source).not.toContain("R{round}")
  })

  it("uses a global evidence board instead of a compressed header workflow strip", () => {
    const source = readSource("components/detect/DetectConsole.tsx")

    expect(source).toContain("GlobalEvidenceBoard")
    expect(source).toContain("全局证据板")
    expect(source).toContain("Evidence Board")
    expect(source).toContain("上传输入")
    expect(source).toContain("创建任务")
    expect(source).toContain("开始检测")
    expect(source).toContain("逻辑质询 Agent vs")
    expect(source).toContain("电子取证 Agent 第")
    expect(source).not.toContain("辩论轮次")
    expect(source).not.toContain("当前决策权重分布")
  })

  it("keeps challenger workflow cards tied to explicit phase events", () => {
    const source = readSource("components/detect/DetectConsole.tsx")

    expect(source).toContain("function isChallengerPhaseLog")
    expect(source).toContain('log.agent === "challenger"')
    expect(source).toContain('log.type === "phase_review"')
    expect(source).toContain('log.type === "challenge"')
    expect(source).toContain("Boolean(CHALLENGER_TARGET_LABELS[log.phase || \"\"])")
    expect(source).toContain('title: "逻辑质询 Agent 活动"')
    expect(source).not.toContain('return `逻辑质询 Agent vs ${phaseTargetLabel(phase)} 第${round}轮`')
  })

  it("prevents the evidence board from duplicating challenger title and raw detail", () => {
    const source = readSource("components/detect/DetectConsole.tsx")

    expect(source).toContain("summarizeChallengerDetail")
    expect(source).toContain("current?.detail ?")
    expect(source).not.toContain("{current?.title || \"等待流程启动\"} · {current?.detail || \"等待检测上下文\"}")
    expect(source).not.toContain("流程进度")
    expect(source).not.toContain("{progress.toFixed(0)}%")
    expect(source).toContain("最近流程")
    expect(source).not.toContain('className="truncate text-xs font-medium text-white/85"')
  })

  it("lets the detection console content expand vertically instead of clipping the agent grid", () => {
    const source = readSource("components/detect/DetectConsole.tsx")

    expect(source).toContain("min-h-screen relative bg-black overflow-x-hidden")
    expect(source).toContain("min-h-[calc(100vh-56px)]")
    expect(source).not.toContain("min-h-screen relative flex flex-col bg-black overflow-hidden")
    expect(source).not.toContain('className="flex-1 w-full relative overflow-hidden"')
    expect(source).not.toContain('className="flex-1 overflow-hidden"')
  })

  it("keeps the requested four-agent quadrant order in the bento scene", () => {
    const source = readSource("components/bento/BentoScene.tsx")
    const forensicsIndex = source.indexOf("Top-Left: Forensics Agent")
    const centerIndex = source.indexOf("Center: Global Evidence Board")
    const challengerIndex = source.indexOf("Top-Right: Challenger Agent")
    const osintIndex = source.indexOf("Bottom-Left: OSINT Agent")
    const commanderIndex = source.indexOf("Bottom-Right: Commander Agent")

    expect(forensicsIndex).toBeGreaterThan(-1)
    expect(centerIndex).toBeGreaterThan(forensicsIndex)
    expect(challengerIndex).toBeGreaterThan(centerIndex)
    expect(challengerIndex).toBeGreaterThan(forensicsIndex)
    expect(osintIndex).toBeGreaterThan(challengerIndex)
    expect(commanderIndex).toBeGreaterThan(osintIndex)
  })

  it("renders a center evidence board with bounded agent panels and no energy ring", () => {
    const bentoSource = readSource("components/bento/BentoScene.tsx")
    const consoleSource = readSource("components/detect/DetectConsole.tsx")

    expect(bentoSource).toContain("evidenceBoardNode")
    expect(bentoSource).toContain("function ConnectionOverlay")
    expect(bentoSource).toContain("agent-connection-line")
    expect(bentoSource).toContain("grid-cols-1 gap-3 lg:grid-cols-[minmax(0,1fr)_minmax(240px,320px)_minmax(0,1fr)]")
    expect(bentoSource).toContain("lg:grid-rows-[520px_120px_520px]")
    expect(bentoSource).toContain("h-[520px]")
    expect(bentoSource).toContain("lg:h-full")
    expect(bentoSource).not.toContain("h-[min(54vh,560px)]")
    expect(bentoSource).not.toContain("min-h-[480px]")
    expect(bentoSource).not.toContain("lg:grid-rows-[520px_minmax(150px,200px)_520px]")
    expect(bentoSource).not.toContain("lg:-mt-4")
    expect(bentoSource).toContain("lg:gap-y-2")
    expect(bentoSource).toContain("overflow-hidden")
    expect(bentoSource).not.toContain("function EnergyRing")
    expect(bentoSource).not.toContain("<EnergyRing")
    expect(consoleSource).toContain("evidenceBoardNode={<GlobalEvidenceBoard steps={workflowSteps} variant=\"center\" />}")
  })

  it("uses compact vertical center evidence board content and DOM-anchored read/write connector paths", () => {
    const bentoSource = readSource("components/bento/BentoScene.tsx")
    const consoleSource = readSource("components/detect/DetectConsole.tsx")

    expect(consoleSource).toContain('compact ? "px-3 py-2" : "px-4 py-3"')
    expect(consoleSource).toContain("const centerSteps = recentSteps.slice(-3)")
    expect(consoleSource).toContain("compact ? centerSteps : recentSteps")
    expect(consoleSource).toContain("compact ? \"mt-2 space-y-1.5\" : \"mt-2 grid gap-2 md:grid-cols-2 xl:grid-cols-4\"")
    expect(consoleSource).toContain('compact ? "mt-2" : "mt-3"')
    expect(bentoSource).not.toContain("readD")
    expect(bentoSource).not.toContain("writeD")
    expect(bentoSource).toContain('kind: "read"')
    expect(bentoSource).toContain('kind: "write"')
    expect(bentoSource).toContain("absolute inset-0 z-[1] hidden h-full w-full lg:block")
    expect(bentoSource).toContain("getBoundingClientRect")
    expect(bentoSource).toContain("ResizeObserver")
    expect(bentoSource).toContain("useLayoutEffect")
    expect(bentoSource).toContain("buildConnectionPath")
    expect(bentoSource).toContain("getReadAnchors")
    expect(bentoSource).toContain("getWriteAnchors")
    expect(bentoSource).toContain("boardRect.top")
    expect(bentoSource).toContain("boardRect.bottom")
    expect(bentoSource).toContain("boardRect.left")
    expect(bentoSource).toContain("boardRect.right")
    expect(bentoSource).toContain("agentRect.left")
    expect(bentoSource).toContain("agentRect.right")
    expect(bentoSource).toContain("agentRect.top")
    expect(bentoSource).toContain("agentRect.bottom")
    expect(bentoSource).not.toContain("viewBox=\"0 0 100 100\"")
    expect(bentoSource).not.toContain("readD: 'M 50 42")
    expect(bentoSource).not.toContain("readD: 'M 50 58")
    expect(bentoSource).not.toContain("readD: 'M 50 39")
    expect(bentoSource).not.toContain("readD: 'M 50 61")
    expect(bentoSource).not.toContain("readD: 'M 50 44")
    expect(bentoSource).not.toContain("readD: 'M 50 56")
    expect(bentoSource).not.toContain("readD: 'M 46 44")
    expect(bentoSource).not.toContain("readD: 'M 54 44")
    expect(bentoSource).not.toContain("readD: 'M 46 56")
    expect(bentoSource).not.toContain("readD: 'M 54 56")
    expect(bentoSource).not.toContain("writeD: 'M 41 50")
    expect(bentoSource).not.toContain("writeD: 'M 59 50")
    expect(bentoSource).not.toContain("22 31")
    expect(bentoSource).not.toContain("78 31")
    expect(bentoSource).not.toContain("22 69")
    expect(bentoSource).not.toContain("78 69")
    expect(bentoSource).not.toContain("28 31")
    expect(bentoSource).not.toContain("72 31")
    expect(bentoSource).not.toContain("29 58")
    expect(bentoSource).not.toContain("71 58")
    expect(bentoSource).toContain("const CONNECTION_STROKE_WIDTH")
    expect(bentoSource).toContain("const CONNECTION_DASH_PATTERN")
    expect(bentoSource).toContain("strokeWidth={isActive ? CONNECTION_STROKE_WIDTH.active : CONNECTION_STROKE_WIDTH.idle}")
    expect(bentoSource).toContain('strokeDasharray={segment.kind === "read" ? CONNECTION_DASH_PATTERN : undefined}')
    expect(bentoSource).toContain("<marker")
    expect(bentoSource).toContain('orient="auto"')
    expect(bentoSource).toContain("markerEnd={`url(#arrow-${segment.agent}-${segment.kind})`}")
    expect(bentoSource).toContain("x: midpointX(agentRect)")
    expect(bentoSource).toContain("x: config.horizontalSide === 'left' ? boardRect.left : boardRect.right")
    const writePathBranch = bentoSource.match(/if \(kind === 'read'\)[\s\S]*?\n\s*}\s*\n\s*return \[([\s\S]*?)\]\.join\(' '\)/)?.[1] ?? ""
    expect(writePathBranch).toContain("`C ${start.x.toFixed(1)} ${(start.y + verticalDirection * verticalBend).toFixed(1)},`")
    expect(writePathBranch).toContain("`${(end.x - horizontalDirection * horizontalBend).toFixed(1)} ${end.y.toFixed(1)},`")
    expect(writePathBranch).not.toContain("`${(start.x + horizontalDirection * horizontalBend).toFixed(1)} ${start.y.toFixed(1)},`")
    expect(writePathBranch).not.toContain("`${end.x.toFixed(1)} ${(end.y - verticalDirection * verticalBend).toFixed(1)},`")
    expect(bentoSource).not.toContain("strokeWidth={isActive ? 0.38 : 0.14}")
    expect(bentoSource).not.toContain('strokeDasharray={segment.kind === "read" ? "1.4 1.6" : undefined}')
    expect(bentoSource).toContain("lineModes?.[segment.agent]")
    expect(bentoSource).toContain("agent-connection-line--active")
    expect(bentoSource).toContain("@keyframes agentLineBreathe")
    expect(bentoSource).toContain("agentLineBreathe 1.8s ease-in-out infinite")
    expect(bentoSource).not.toContain('strokeDasharray={isActive ? "0" : "1.5 1.8"}')
    expect(bentoSource).not.toContain("M 24 24 L 50 50")
    expect(bentoSource).not.toContain("M 31 31 C 34 30, 38 42, 50 50")
    expect(bentoSource).not.toContain("33 44, 31 40")
    expect(bentoSource).not.toContain("67 44, 69 40")
    expect(bentoSource).not.toContain("33 56, 31 60")
    expect(bentoSource).not.toContain("67 56, 69 60")
    expect(bentoSource).not.toContain("writeD: 'M 36 36")
    expect(bentoSource).not.toContain("writeD: 'M 64 64")
  })

  it("keeps agent log wrappers as full-height flex children in the bento cards", () => {
    const source = readSource("components/detect/DetectConsole.tsx")

    expect(source).toContain("function AgentLogPanel")
    expect(source).toContain("const logsByAgent = useMemo")
    expect(source).toContain("<AgentLogPanel logs={logsByAgent.osint} />")
    expect(source).toContain("<AgentLogPanel logs={logsByAgent.forensics} />")
    expect(source).toContain("<AgentLogPanel logs={logsByAgent.challenger} />")
    expect(source).toContain("<AgentLogPanel logs={logsByAgent.commander} />")
    expect(source).toContain("flex h-full w-full max-w-full min-h-0 min-w-0 flex-1 basis-0 flex-col rounded-xl liquid-glass")
    expect(source).toContain("overflow-hidden box-border")
    expect(source).not.toContain('<AgentLogPanel logs={logs.filter')
    expect(source).not.toContain("{finalVerdict && <div className=\"shrink-0\"><VerdictBadge verdict={finalVerdict} /></div>}")
  })

  it("keeps agent log content width fluid instead of reserving fixed horizontal space", () => {
    const source = readSource("components/agents/AgentLog.tsx")

    expect(source).toContain("flex h-full w-full max-w-full min-h-0 min-w-0 flex-1 basis-0 flex-col overflow-hidden box-border")
    expect(source).toContain("h-full w-full max-h-full max-w-full min-h-0 min-w-0 flex-1 basis-0 overflow-y-auto overscroll-contain font-mono text-xs box-border")
    expect(source).toContain('data-testid="agent-log-content"')
    expect(source).toContain("w-full max-w-full min-w-0 space-y-2")
    expect(source).toContain('data-testid="agent-log-entry"')
    expect(source).toContain('data-testid="agent-log-entry-content"')
    expect(source).toContain("grid w-full max-w-full min-w-0 grid-cols-[2px_minmax(0,1fr)]")
    expect(source).toContain("block w-full max-w-full min-w-0")
    expect(source).toContain('style={{ scrollbarGutter: "stable" }}')
    expect(source).toContain("[word-break:break-word]")
    expect(source).not.toContain("AnimatePresence")
    expect(source).not.toContain("height: 0")
    expect(source).not.toContain('height: "auto"')
    expect(source).not.toContain("scrollIntoView")
    expect(source).not.toContain("TypewriterText")
    expect(source).not.toContain("typewriter-")
    expect(source).not.toContain("space-y-2 pr-2 font-mono")
    expect(source).not.toContain('className="flex w-full max-w-full min-w-0 gap-2 items-start"')
  })

  it("keeps agent summary cards at a stable height above the output panels", () => {
    const source = readSource("components/agents/AgentCard.tsx")

    expect(source).toContain("glass-card min-h-[122px]")
    expect(source).toContain("flex min-w-0 items-center justify-between gap-3")
    expect(source).toContain("flex shrink-0 items-center gap-1.5")
  })

  it("lets graph and citation panels use the available vertical space", () => {
    const source = readSource("components/detect/ProvenanceGraphView.tsx")

    expect(source).toContain("min-h-[calc(100vh-88px)]")
    expect(source).toContain("lg:grid-cols-[minmax(0,1fr)_320px]")
    expect(source).toContain("flex-1 min-h-0 overflow-auto")
    expect(source).not.toContain("max-h-44")
  })

  it("keeps collaboration controls role-scoped and exposes the new context fields", () => {
    const panelSource = readSource("components/collaboration/ExpertPanel.tsx")
    const streamSource = readSource("hooks/useAgentStream.ts")
    const consoleSource = readSource("components/detect/DetectConsole.tsx")

    expect(streamSource).toContain("consultation_approval_required")
    expect(streamSource).toContain("consultation_started")
    expect(streamSource).toContain("consultation_summary_pending")
    expect(streamSource).toContain("consultation_summary_confirmed")
    expect(streamSource).toContain("consultation_skipped")
    expect(streamSource).toContain("consultation_resumed")
    expect(panelSource).toContain("canModerateConsultation(currentRole)")
    expect(panelSource).toContain("结束协同")
    expect(panelSource).toContain("确认摘要并交给 Commander")
    expect(panelSource).toContain("message_type")
    expect(panelSource).toContain("anchor_agent")
    expect(panelSource).not.toContain("suggested_action")
    expect(panelSource).not.toContain("阶段 / phase")
    expect(panelSource).toContain("协同上下文")
    expect(panelSource).toContain("expertTasks")
    expect(consoleSource).toContain("consultationState={consultationState}")
  })

  it("uses human collaboration wording while keeping legacy consultation events compatible", () => {
    const panelSource = readSource("components/collaboration/ExpertPanel.tsx")
    const streamSource = readSource("hooks/useAgentStream.ts")
    const consoleSource = readSource("components/detect/DetectConsole.tsx")

    expect(streamSource).toContain("collaboration_required")
    expect(streamSource).toContain("consultation_required")
    expect(consoleSource).toContain("打开协同面板")
    expect(consoleSource).toContain("收起协同面板")
    expect(consoleSource).not.toContain("打开会诊面板")
    expect(panelSource).toContain("人机协同面板")
    expect(panelSource).toContain("协同上下文")
    expect(panelSource).toContain("结束协同")
    expect(panelSource).toContain("再次协同")
    expect(panelSource).not.toContain("专家会诊频道")
  })

  it("turns off starfield rotation only in the timeline view", () => {
    const source = readSource("components/detect/DetectConsole.tsx")

    expect(source).toContain('const backgroundRotationSpeed = viewMode === "timeline" ? 0 : 0.05')
    expect(source).toContain("rotationSpeed={backgroundRotationSpeed}")
  })
})
